# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servico.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservico.proto\"\x1d\n\rEnvioMensagem\x12\x0c\n\x04nome\x18\x01 \x01(\t\"\x1c\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\xdd\x01\n\x0cRotaMensagem\x12*\n\x0bGetMensagem\x12\x0e.EnvioMensagem\x1a\t.Resposta\"\x00\x12\x34\n\x13ListMensagemCliente\x12\x0e.EnvioMensagem\x1a\t.Resposta\"\x00\x30\x01\x12\x34\n\x11ListMensagemAmbos\x12\x0e.EnvioMensagem\x1a\t.Resposta\"\x00(\x01\x30\x01\x12\x35\n\x14ListMensagemServidor\x12\x0e.EnvioMensagem\x1a\t.Resposta\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servico_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENVIOMENSAGEM']._serialized_start=17
  _globals['_ENVIOMENSAGEM']._serialized_end=46
  _globals['_RESPOSTA']._serialized_start=48
  _globals['_RESPOSTA']._serialized_end=76
  _globals['_ROTAMENSAGEM']._serialized_start=79
  _globals['_ROTAMENSAGEM']._serialized_end=300
# @@protoc_insertion_point(module_scope)
